# -*- coding: utf-8 -*-
"""Jawaban TTS alpro_Nuri Ghania_F0403251017

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKDo4inwDpvddtzLTkPX0Y4zsSwoMOkp
"""

# panen.py
def hitung_total_panen(jumlah_karung, berat_per_karung):
    return jumlah_karung * berat_per_karung

if __name__ == "__main__":
    karung = 10
    berat = 50
    total = hitung_total_panen(karung, berat)
    print(f"Total berat hasil panen: {total} kg")